# Generated by Django 4.2.1 on 2023-05-16 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='created_by',
            new_name='created_user',
        ),
    ]
